name: bible_stories
description: "Interactive Bible Stories App for Kids"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  lottie: ^3.1.2
  confetti: ^0.7.0
  cached_network_image: ^3.3.1

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Local Storage (Offline)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Audio
  flutter_tts: ^4.0.2
  audioplayers: ^6.0.0

  # Navigation
  go_router: ^14.2.7

  # Localization
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.11
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true
  generate: true

  # assets:
    # - assets/images/
    # - assets/images/stories/
    # - assets/audio/
    # - assets/lottie/

  # fonts:
  #   - family: Nunito
  #     fonts:
  #       - asset: assets/fonts/Nunito-Regular.ttf
  #       - asset: assets/fonts/Nunito-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Nunito-SemiBold.ttf
  #         weight: 600
  #   - family: NotoSansEthiopic
  #     fonts:
  #       - asset: assets/fonts/NotoSansEthiopic-Regular.ttf
  #       - asset: assets/fonts/NotoSansEthiopic-Bold.ttf
  #         weight: 700
